# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1e\n\rEmailResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1e\n\rPhoneResponse\x12\r\n\x05phone\x18\x01 \x01(\t2u\n\x0b\x41uthService\x12\x32\n\x08GetEmail\x12\x11.auth.UserRequest\x1a\x13.auth.EmailResponse\x12\x32\n\x08GetPhone\x12\x11.auth.UserRequest\x1a\x13.auth.PhoneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=20
  _globals['_USERREQUEST']._serialized_end=50
  _globals['_EMAILRESPONSE']._serialized_start=52
  _globals['_EMAILRESPONSE']._serialized_end=82
  _globals['_PHONERESPONSE']._serialized_start=84
  _globals['_PHONERESPONSE']._serialized_end=114
  _globals['_AUTHSERVICE']._serialized_start=116
  _globals['_AUTHSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
